[package]
name = "cortexm"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../kernel" }
capsules-core = { path = "../../capsules/core" }